SET TRANSACTION ISOLATION LEVEL READ COMMITTED

GOGO
IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'UK_RfIdMst' AND object_id = OBJECT_ID('RfIdMst'))
	Create Unique Index UK_RfIdMst on RfIdMst (RimByy, RimBChr, RimBNo)
GOGO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED


