SET TRANSACTION ISOLATION LEVEL READ COMMITTED

GOGO

alter table InvHd Alter Column INHCUSTREM varchar(800) NOT NULL
alter table Head Alter Column HCUSTREM varchar(800) NOT NULL


GOGO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED


